CREATE TABLE users (
	userId       INT NOT NULL AUTO_INCREMENT,
	firstName    VARCHAR(50) NOT NULL,
	lastName     VARCHAR(50) NOT NULL,
	emailAddress VARCHAR(50) NOT NULL,
	password     VARCHAR(64) NOT NULL,
	PRIMARY KEY (userId)
);

GRANT ALL PRIVILEGES ON *.* TO 'test'@'192.168.0.25' IDENTIFIED BY 'test' WITH GRANT OPTION;